### PR TITLE
table building and machine tags with gh actions

### PR DESCRIPTION
**Pull request by jhnwllr**
Adds automatic  

* table building 
* machine tagging of private sector publishers and datasets

with gh actions.

### CODE REVIEW

**Comment by MattBlissett** [comment]
Pending the improvement to the UI in the issue linked above, Annie will be able to maintain the private sector data directly in the registry. I've already added the necessary permission to the machine tag namespace to her account.

**Comment by jhnwllr** [comment]
Javier wants to maybe move this table somewhere else. We have a meeting about it next week. But I assume the information will still be maintained through machine tags.

**Comment by MattBlissett** [comment]
This will need adjusting to take the data only from the machine tags in the registry.

I've tweaked the format so the table can be translated automatically, without the translators needed to 'translate' the organization titles and the numbers.  It's now just CSV, which I hope is also easier. The translators will translate "Mining" and so on separately, in sectors.en.txt.

Can you also adjust the script to output in this structure?

`250-private-sector-table.csv`
```
"https://www.gbif.org/publisher/f2429cd1-4d45-475c-852a-892024cb4aba[ARC - Arctic Research and Consulting DA]",{CONSULTING},{NO},1,8 914,63
...
```
Note no header row. I used U+202F NARROW NO-BREAK SPACE for the thousands separator, as it fits our style guide and then doesn't need translating.

`260-private-sector-totals.csv`
```
437,8 897 634,7 976
```
Similarly for the thousands separator.

**Comment by jhnwllr** [comment]
Table builds seem to work from machineTags only now. This requires that new datasets and publishers get machineTags added in the registry. 
https://github.com/gbif/doc-private-sector-data-publishing/issues/25

**Pull request merged**
